config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  
  belongs_to :user
  validates_presence_of :text
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.order('updated_at DESC').page(params[:page]).per(5)
  end
  
  def new
  end
  
  def create
    if text_confirmation
      redirect_to new_tweet_path, alert: '▼ Please enter the text.'
      
    else
      Tweet.create(text: tweet_params[:text], user_id: current_user.id)
      redirect_to :root, alert: '▼ Posted!'
    end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    if text_confirmation
      redirect_to "/tweets/#{params[:id]}/edit", alert: '▼ Please enter the text.'
    else
      tweet = Tweet.find(params[:id])
      tweet.update(text: tweet_params[:text])
      redirect_to :root, alert: '▼ Updated!'
    end
  end
  
  def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to :root, alert: '▼ Deleted!'
  end
  
  private
  def tweet_params
    params.permit(:text)
  end
  
  def text_confirmation
    text = params.permit(:text)
    return text[:text].blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="brand">
      <h2><a href='/'>Blog</a></h2>
    </div>
    <div class="header_button">
      <ul class="sign_button">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'SignOut', destroy_user_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to 'New', new_tweet_path %>
          </li>
        <% else %>
          <li>
            <%= link_to 'SignUp', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'SignIn', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </header>
  <h4 class="alert"><%= flash[:alert] %></h4>
    <%= yield %>
  <footer>
    <p>© 2019 Riki inc.</p>
  </footer>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="content">
  <p class="posted_time">
  Created at <%= tweet.created_at %>, Updated at <%= tweet.updated_at %>
  </p>
  <div class="text">
    <%= simple_format(tweet.text) %>
  </div>
  <div class="button">
    <ul>
      <li>
        <%= link_to 'show', "/tweets/#{tweet.id}", method: :get %>
      </li>
      <% if user_signed_in? && tweet.user_id == current_user.id %>
        <li>
          <%= link_to 'edit', "/tweets/#{tweet.id}/edit", method: :get%>
        </li>
        <li>
          <%= link_to 'destroy', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents">
  <%= form_for(@tweet, method: :patch) do %>
    <textarea name="text" rows="30" cols="60"><%= @tweet.text %></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents">
  <% @tweets.each do |tweet| %>
    <%= render partial: 'tweet', locals: {tweet: tweet} %>
  <% end %>
  <%= paginate @tweets %>
</div>

app/views/tweets/new.html.erb
<%= form_tag(tweets_path, method: :post) do %>
  <h3>
    New
  </h3>
  <textarea name="text" placeholder="text" rows="30" cols="60"></textarea>
  <input type="submit" value="SENT">
<% end %>

app/views/tweets/show.html.erb
<div class="contents">
  <div class="content">
    <div class="text">
      <%= simple_format(@tweet.text) %>
    </div>
    <div class="button">
      <ul>
        <% if user_signed_in? && @tweet.user_id == current_user.id %>
          <li>
            <%= link_to 'edit', "/tweets/#{@tweet.id}/edit", method: :get%>
          </li>
          <li>
            <%= link_to 'destroy', "/tweets/#{@tweet.id}", method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>